# Generated by Django 4.2.7 on 2023-12-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacimiento', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Actividades',
            new_name='Actividad',
        ),
        migrations.RenameModel(
            old_name='Sedes',
            new_name='Sede',
        ),
        migrations.DeleteModel(
            name='Socios',
        ),
    ]
